### PR TITLE
add bernoulli_process

### PR DESCRIPTION
**Pull request by grudloff**
This solves #200

### CODE REVIEW

**Comment by grudloff** [comment]
@SigmaX Most of the tests are passing and I believe this is working fine. But for some obscure reason, a couple are failing and I can't seem to figure out why. I get test fails like this one:
```
Test result not found for: ./tests/real_rep/test_ops.py::test_mutate_gaussian
```
I believe the issue must be with the vs studio code, rather than an actual test fail. I will try to solve this later.

**Comment by markcoletti** [comment]
@SigmaX you seem to know what's going on with this merge request.  Can you please resolve it when ya get a chance?  Thanks!

**Comment by SigmaX** [comment]
Finally picking this up!  I've started cherry-picking the changes into a new branch that branches off `develop` (since we won't want to put this straight into `master`).

There will be a few merge conflicts to resolve, and I'll want to make sure we have good test coverage.

**Comment by SigmaX** [comment]
This has been a good opportunity to improve test coverage of the operators so we can refactor with confidence.

I've integrated it into the `binary_rep` operators in a separate branch.  What remains is to do the same for `real_rep` and `int_rep`, at which point I'll close this and open a new PR.

**Comment by SigmaX** [comment]
Got all the changes integrated and unit tests are happy, but the `examples/` tests are displeased:

image

**Comment by SigmaX** [comment]
Fixed—just missed a size check that needed updated in `genome_mutate_gaussian().`

New PR created at #232 — closing this one.

**Pull request closed without merging**
