### PR TITLE
Added SUS selection, tests, and refactored proportional selection

### LINKED ISSUE #145: Add stochastic universal sampling (SUS)
Implement as:

```python3
@curry
@listiter_op
def sus_selection(population: List, n=None, shuffle=True, key=lambda x: x.fitness) -> Iterator
```

This will take a `population` of individuals and randomly find `n` evenly spaced points from which to sample the `population`.

Once all of the `n` points have been sampled you can choose to `shuffle` and resample or just resample by cycling through the existing points, allowing for an endless selection method.

A different selection criteria can be used by changing `key`.

Statistically_Uniform

This is an example with `n=4` where individuals A, B, C, and F are selected. If `shuffle=True` here then a new 4 points would be generated. If `shuffle=False` here then selection would cycle: `A -> B -> C -> F -> A -> B ...`

### PR DESCRIPTION
**Pull request by thomashopkins32**
Added implementation of SUS selection mentioned in #145. Made some refactoring changes to `proportional_selection` since `sus_selection` handles negative fitness in the same way. Discussion on that also mentioned in #145. Maybe move this helper function to `utils.py` or something similar?

Let me know if you have any suggestions/improvements.

Thanks!

Closes #145

### CODE REVIEW

**Comment by thomashopkins32** [comment]
Just a thought but I think it might be worth it to change the implementation for `proportional_selection` to be

```python3
def proportional_selection(population: List, ...):
    yield from sus_selection(population, n=1, shuffle=True, ...)
```

Am I wrong to think that these would be equivalent?

**Comment by piprrr** [comment]
> Added implementation of SUS selection mentioned in #145. Made some refactoring changes to `proportional_selection` since `sus_selection` handles negative fitness in the same way. Discussion on that also mentioned in #145. Maybe move this helper function to `utils.py` or something similar?
> 
> Let me know if you have any suggestions/improvements.
> 
> Thanks!
> 
> Closes #145

I'm thinking the helper function is probably best where it is since it's esoteric in that it's only applicable for proportional selection.  If anything renaming it to have a leading `_` indicates that it's a private helpful function not intended for use outside the module.

**Comment by piprrr** [comment]
> Just a thought but I think it might be worth it to change the implementation for `proportional_selection` to be
> 
> ```python
> def proportional_selection(population: List, ...):
>     yield from sus_selection(population, n=1, shuffle=True, ...)
> ```
> 
> Am I wrong to think that these would be equivalent?

These would actually not be equivalent, so they should still be kept separate.  The variances between the two implementations will be quite different, hence Siggy suggesting today of making a jupyter notebook to compare the variances between different selection operators.

**Comment by piprrr** [comment]
Looks good, and I should get in the habit preferring `numpy` for my numeric vector/array needs.

**Comment by SigmaX** [comment]
@piprrr Thomas’s suggestion was to use SUS as a subroutine, but to call it to produce just *one sample.*. So it would in fact be equivalent to plain propportional selection.

In any event, though; I agree that a helper function is more readable.

**Pull request merged**
